export default {
  success: true,
  data: {
    clubs: [
      {
        id: 1,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/4us2nCgl6kgZc0t3hpW75Q_48x48.png",
        name: "Arsenal",
        mp: 19,
        w: 16,
        d: 2,
        l: 1,
        gf: 45,
        ga: 16,
        gd: 29,
        pts: 50,
        last5: ["good", "good", "null", "good", "good"],
      },
      {
        id: 2,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/z44l-a0W1v5FmgPnemV6Xw_48x48.png",
        name: "Man City",
        mp: 20,
        w: 14,
        d: 3,
        l: 3,
        gf: 53,
        ga: 20,
        gd: 33,
        pts: 45,
        last5: ["good", "good", "bad", "good", "null"],
      },
      {
        id: 3,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/96CcNNQ0AYDAbssP0V9LuQ_48x48.png",
        name: "Newcastle",
        mp: 20,
        w: 10,
        d: 9,
        l: 1,
        gf: 33,
        ga: 11,
        gd: 22,
        pts: 39,
        last5: ["null", "good", "null", "null", "good"],
      },
      {
        id: 4,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/udQ6ns69PctCv143h-GeYw_48x48.png",
        name: "Man United",
        mp: 20,
        w: 12,
        d: 3,
        l: 5,
        gf: 32,
        ga: 25,
        gd: 7,
        pts: 39,
        last5: ["bad", "null", "good", "good", "good"],
      },
      {
        id: 5,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/k3Q_mKE98Dnohrcea0JFgQ_48x48.png",
        name: "Tottenham",
        mp: 21,
        w: 11,
        d: 3,
        l: 7,
        gf: 40,
        ga: 31,
        gd: 9,
        pts: 36,
        last5: ["good", "bad", "bad", "good", "bad"],
      },
      {
        id: 6,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/EKIe0e-ZIphOcfQAwsuEEQ_48x48.png",
        name: "Brighton",
        mp: 19,
        w: 9,
        d: 4,
        l: 6,
        gf: 37,
        ga: 27,
        gd: 10,
        pts: 31,
        last5: ["null", "good", "good", "bad", "good"],
      },
      {
        id: 7,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/Gh7_5p3n364p4vxeM8FhNg_48x48.png",
        name: "Fulham",
        mp: 21,
        w: 9,
        d: 4,
        l: 8,
        gf: 32,
        ga: 30,
        gd: 2,
        pts: 31,
        last5: ["bad", "bad", "good", "good", "good"],
      },
      {
        id: 8,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/QOUce0WQBYqnkSmN6_TxGA_48x48.png",
        name: "Brentford",
        mp: 19,
        w: 16,
        d: 2,
        l: 1,
        gf: 45,
        ga: 16,
        gd: 29,
        pts: 50,
        last5: ["null", "good", "good", "good", "null"],
      },
      {
        id: 9,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/0iShHhASp5q1SL4JhtwJiw_48x48.png",
        name: "Liverpool",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "bad", "bad", "good", "good"],
      },
      {
        id: 10,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/fhBITrIlbQxhVB6IjxUO6Q_48x48.png",
        name: "Chelsea",
        mp: 20,
        w: 8,
        d: 5,
        l: 7,
        gf: 22,
        ga: 21,
        gd: 1,
        pts: 29,
        last5: ["null", "good", "bad", "bad", "null"],
      },
      {
        id: 11,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/uyNNelfnFvCEnsLrUL-j2Q_48x48.png",
        name: "Aston Villa",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["good", "good", "null", "good", "bad"],
      },
      {
        id: 12,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/8piQOzndGmApKYTcvyN9vA_48x48.png",
        name: "Crystal Palace",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "null", "bad", "bad", "good"],
      },
      {
        id: 13,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/Zr6FbE-8pDH7UBpWCO8U9A_48x48.png",
        name: "Nottm Forest",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "good", "good", "null", "bad"],
      },
      {
        id: 14,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/0iShHhASp5q1SL4JhtwJiw_48x48.png",
        name: "Liverpool",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "bad", "bad", "good", "good"],
      },
      {
        id: 15,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/5dqfOKpjjW6EwTAx_FysKQ_48x48.png",
        name: "Leeds United",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "bad", "null", "null", "bad"],
      },
      {
        id: 16,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/bXkiyIzsbDip3x2FFcUU3A_48x48.png",
        name: "West Ham",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["good", "bad", "null", "bad", "bad"],
      },
      {
        id: 17,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/-WjHLbBIQO9xE2e2MW3OPQ_48x48.png",
        name: "Wolves",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["bad", "good", "null", "bad", "good"],
      },
      {
        id: 18,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/IcOt-hrK04B-RlRwI3R0yA_48x48.png",
        name: "Bournemouth",
        mp: 19,
        w: 8,
        d: 5,
        l: 6,
        gf: 34,
        ga: 25,
        gd: 9,
        pts: 29,
        last5: ["null", "bad", "bad", "bad", "bad"],
      },
      {
        id: 19,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/C3J47ea36cMBc4XPbp9aaA_48x48.png",
        name: "Everton",
        mp: 20,
        w: 3,
        d: 6,
        l: 11,
        gf: 15,
        ga: 28,
        gd: -13,
        pts: 15,
        last5: ["bad", "bad", "bad", "null", "bad"],
      },
      {
        id: 20,
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/y1V4sm2SEBiWUPRIYl5rfg_48x48.png",
        name: "Liverpool",
        mp: 20,
        w: 4,
        d: 3,
        l: 17,
        gf: 34,
        ga: 35,
        gd: 18,
        pts: 15,
        last5: ["bad", "good", "bad", "bad", "bad"],
      },
    ],
  },
};
